// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN-K2eOe5bYCqWcepqhDPCN4TR-2_jpY8',
    appId: '1:445240699224:web:d5d0c096ad0f31f6a75d2d',
    messagingSenderId: '445240699224',
    projectId: 'themeremoteconfig',
    authDomain: 'themeremoteconfig.firebaseapp.com',
    storageBucket: 'themeremoteconfig.appspot.com',
    measurementId: 'G-BNVGX04RC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNUE4CEYEBSVl5l1yZn3zXldg9s0XaNEQ',
    appId: '1:445240699224:android:8fd2cc01ccc93c1ea75d2d',
    messagingSenderId: '445240699224',
    projectId: 'themeremoteconfig',
    storageBucket: 'themeremoteconfig.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0o4HWCU44SRZoxvO5b93DEJr0ECnvICQ',
    appId: '1:445240699224:ios:501e8c22033ad79ba75d2d',
    messagingSenderId: '445240699224',
    projectId: 'themeremoteconfig',
    storageBucket: 'themeremoteconfig.appspot.com',
    iosBundleId: 'com.example.remoteconfig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0o4HWCU44SRZoxvO5b93DEJr0ECnvICQ',
    appId: '1:445240699224:ios:e1417ba44b753d40a75d2d',
    messagingSenderId: '445240699224',
    projectId: 'themeremoteconfig',
    storageBucket: 'themeremoteconfig.appspot.com',
    iosBundleId: 'com.example.remoteconfig.RunnerTests',
  );
}
